### PR TITLE
Styles for result components

### PR DESCRIPTION
**Pull request by mdelapenya**
Please remove last commit as it's just for testing purpose, removing home components to add there a Results one

### CODE REVIEW

**Comment by mdelapenya** [comment]
Of course, please make up the markup/css styles as you prefer!

**Comment by javierlopezdeancos** [comment]
looks good to me :+1:

**Comment by javierlopezdeancos** [comment]
we need move the actual containers to components and write redux container to control all data/stores/dispach/ flow

**Comment by mdelapenya** [comment]
Yes, as we saw yesterday, the container is an abstraction, like a pipe from the store to the model view, not a regular 'view' component

**Pull request merged**
